# Site settings
title: Derek Hu's Blog
email: derek.dchu@gmail.com
description: The contents of this website are Â© 2014 Dicong Hu 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://derek.me" # the base hostname & protocol for your site
#twitter_username:
github_username:  derek-dchu
linkedin_url: https://www.linkedin.com/profile/view?id=219339695

# Build settings
markdown: kramdown

# Github Pages settings
highlighter: pygments

safe: true
lsi: false

# Personal settings
author_name: Derek Hu
author_bio: "Love Thinking, Love Hacking, Love NYC<br>I am a full stack developer in New York City"